# Generated by Django 4.0 on 2021-12-09 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_apply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='job',
        ),
    ]
